#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

VERSION="v2.1.7"
URL="https://github.com/Leantime/leantime/releases/download/$VERSION/Leantime-$VERSION.tar.gz"

dl $URL /usr/local/src
