#!/bin/bash -eux

dl() {
    local proxy_args=()
    [ -n "${FAB_HTTP_PROXY:-}" ] && proxy_args=(--proxy "$FAB_HTTP_PROXY")
    cd "$2"
    curl --proto '=https' --tlsv1.2 -L -f -O "${proxy_args[@]}" "$1"
    cd -
}

VERSION=v3.9.8
SHA256=7977f0477efec844b667676345ab06b0697a1cd1352aa698999af018c2c99d52
URL="https://github.com/Leantime/leantime/releases/download/$VERSION/Leantime-$VERSION.tar.gz"

dl "$URL" /usr/local/src
echo "$SHA256  /usr/local/src/Leantime-$VERSION.tar.gz" \
    | sha256sum --check --strict
