#!/bin/bash -e
# regenerate leantime secrets and mysql user password

. /etc/default/inithooks

WEBROOT=/var/www/leantime
CONF=$WEBROOT/config/configuration.php

DB_USER=leantime
DB_PASS=$(mcookie)

sed -i "\|\$dbPassword =|s|=.*|=\"$DB_PASS\";|" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user="$DB_USER" --pass="$DB_PASS"

sed -i "\|\$sessionpassword =|s|=.*|=\"$(mcookie)$(mcookie)\";|" $CONF
